class AppLocalization {
  final String language;

  AppLocalization(this.language);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'already_have_account': 'Already have an account?',
      'cancel': 'Cancel',
      'confirm_logout': 'Are you sure you want to logout?',
      'copied_to_clipboard': 'Copied to clipboard',
      'create_account': 'Create Account',
      'describe_placeholder': 'Describe the prompt you want to create...',
      'describe_prompts_subtitle': 'Describe what you want and get optimized prompts for any AI tool.',
      'dont_have_account': "Don't have an account?",
      'edit': 'Edit',
      'enter_email': 'Enter your email',
      'coding': 'Coding',
      'generate_better_prompts': 'Generate Better AI Prompts',
      'generate_prompt': 'Generate Prompt',
      'marketing': 'Marketing',

      'get_started': 'Get Started',
      'language': 'Language',
      'login': 'Login',
      'logout': 'Logout',
      'new_chat': 'New Chat',
      'onboarding_slide1_subtitle': 'Generate powerful prompts for any AI tool with ease',
      'onboarding_slide1_title': 'AI Prompt Generator',
      'onboarding_slide2_subtitle': 'Craft the perfect prompt step-by-step with our guided flow',
      'onboarding_slide2_title': 'Step-by-Step Guidance',
      'onboarding_slide3_subtitle': 'Supports Hindi, Marathi, Gujarati and more Indian languages',
      'onboarding_slide3_title': 'Multi-Language Support',
      'or_continue_with': 'Or continue with',
      'password': 'Password',
      'pre_prompts': 'Pre Prompts',
      'profile': 'Profile',
      'prompt_types': 'Prompt Types',
      'recent_chats': 'Recent Chats',
      'register': 'Register',
      'roll_back': 'Roll Back',
      'settings': 'Settings',
      'sign_in_continue': 'Sign in to continue',
      'sign_up': 'Sign Up',
      'sign_up_to_start': 'Sign up to get started',
      'skip': 'Skip',
      'stop_responding': 'Stop Responding',
      'thinking': 'Thinking...',
      'try_prompt_1': 'Create a prompt for writing viral tweets',
      'try_prompt_2': 'Generate Midjourney image prompt',
      'try_prompt_3': 'Create a marketing prompt for product launch',
      'try_prompt_4': 'Generate AI prompt for a blog outline',
      'try_prompts': 'Try prompts',
      'type_message': 'Type a message...',
      'welcome_back': 'Welcome Back',
      'welcome_subtitle': 'Your AI-powered prompt generation assistant',
      'welcome_to': 'Welcome to Vakya Pro',
      'yes': 'Yes',
    },
    'hi': {
      'already_have_account': 'पहले से खाता है?',
      'cancel': 'रद्द करें',
      'confirm_logout': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'copied_to_clipboard': 'क्लिपबोर्ड पर कॉपी किया',
      'create_account': 'खाता बनाएं',
      'describe_placeholder': 'वह प्रॉम्प्ट बताएं जो आप बनाना चाहते हैं...',
      'describe_prompts_subtitle': 'जो चाहते हैं उसे बताएं और किसी भी AI टूल के लिए ऑप्टिमाइज़ प्रॉम्प्ट पाएं।',
      'dont_have_account': 'खाता नहीं है?',
      'edit': 'संपादित करें',
      'enter_email': 'ईमेल दर्ज करें',
      'coding': 'कोडिंग',
      'generate_better_prompts': 'बेहतर AI प्रॉम्प्ट बनाएं',
      'generate_prompt': 'प्रॉम्प्ट बनाएं',
      'marketing': 'मार्केटिंग',
      'get_started': 'शुरू करें',
      'language': 'भाषा',
      'login': 'लॉगिन',
      'logout': 'लॉगआउट',
      'new_chat': 'नई चैट',
      'onboarding_slide1_subtitle': 'किसी भी AI टूल के लिए आसानी से शक्तिशाली प्रॉम्प्ट बनाएं',
      'onboarding_slide1_title': 'AI प्रॉम्प्ट जनरेटर',
      'onboarding_slide2_subtitle': 'हमारी गाइडेड प्रक्रिया से कदम-दर-कदम सही प्रॉम्प्ट तैयार करें',
      'onboarding_slide2_title': 'चरण-दर-चरण मार्गदर्शन',
      'onboarding_slide3_subtitle': 'हिंदी, मराठी, गुजराती और अधिक भारतीय भाषाओं का समर्थन करता है',
      'onboarding_slide3_title': 'बहुभाषा समर्थन',
      'or_continue_with': 'या इससे जारी रखें',
      'password': 'पासवर्ड',
      'pre_prompts': 'पूर्व-निर्धारित प्रॉम्प्ट',
      'profile': 'प्रोफ़ाइल',
      'prompt_types': 'प्रॉम्प्ट प्रकार',
      'recent_chats': 'हाल की चैट',
      'register': 'पंजीकरण करें',
      'roll_back': 'वापस करें',
      'settings': 'सेटिंग्स',
      'sign_in_continue': 'जारी रखने के लिए साइन इन करें',
      'sign_up': 'साइन अप',
      'sign_up_to_start': 'शुरू करने के लिए साइन अप करें',
      'skip': 'छोड़ें',
      'stop_responding': 'रोकें',
      'thinking': 'सोच रहा हूँ...',
      'try_prompt_1': 'वायरल ट्वीट लिखने के लिए प्रॉम्प्ट बनाएं',
      'try_prompt_2': 'Midjourney इमेज प्रॉम्प्ट बनाएं',
      'try_prompt_3': 'उत्पाद लॉन्च के लिए मार्केटिंग प्रॉम्प्ट बनाएं',
      'try_prompt_4': 'ब्लॉग आउटलाइन के लिए AI प्रॉम्प्ट बनाएं',
      'try_prompts': 'प्रॉम्प्ट आज़माएं',
      'type_message': 'संदेश लिखें...',
      'welcome_back': 'वापस स्वागत है',
      'welcome_subtitle': 'आपका AI-संचालित प्रॉम्प्ट जनरेशन सहायक',
      'welcome_to': 'Vakya Pro में आपका स्वागत है',
      'yes': 'हाँ',
    },
    'mr': {
      'already_have_account': 'आधीच खाते आहे?',
      'cancel': 'रद्द करा',
      'confirm_logout': 'तुम्हाला खरोखर लॉगआउट करायचे आहे का?',
      'copied_to_clipboard': 'क्लिपबोर्डवर कॉपी केले',
      'create_account': 'खाते तयार करा',
      'describe_placeholder': 'तुम्हाला कोणता प्रॉम्प्ट तयार करायचा आहे ते सांगा...',
      'describe_prompts_subtitle': 'तुम्हाला काय हवे ते सांगा आणि कोणत्याही AI टूलसाठी ऑप्टिमाइझ प्रॉम्प्ट मिळवा.',
      'dont_have_account': 'खाते नाही?',
      'edit': 'संपादित करा',
      'enter_email': 'ईमेल प्रविष्ट करा',
      'coding': 'कोडिंग',
      'generate_better_prompts': 'बेहतर AI प्रॉम्प्ट तयार करा',
      'generate_prompt': 'प्रॉम्प्ट तयार करा',
      'marketing': 'मार्केटिंग',
      'get_started': 'सुरू करा',
      'language': 'भाषा',
      'login': 'लॉगिन',
      'logout': 'लॉगआउट',
      'new_chat': 'नवीन चॅट',
      'onboarding_slide1_subtitle': 'कोणत्याही AI साधनासाठी सहजपणे शक्तिशाली प्रॉम्प्ट तयार करा',
      'onboarding_slide1_title': 'AI प्रॉम्प्ट जनरेटर',
      'onboarding_slide2_subtitle': 'आमच्या मार्गदर्शित प्रक्रियेसह पायरीपायरी योग्य प्रॉम्प्ट तयार करा',
      'onboarding_slide2_title': 'टप्प्याटप्प्याने मार्गदर्शन',
      'onboarding_slide3_subtitle': 'हिंदी, मराठी, गुजराती आणि इतर भारतीय भाषांना समर्थन करते',
      'onboarding_slide3_title': 'बहुभाषा समर्थन',
      'or_continue_with': 'किंवा याद्वारे सुरू ठेवा',
      'password': 'पासवर्ड',
      'pre_prompts': 'पूर्व-निर्धारित प्रॉम्प्ट',
      'profile': 'प्रोफाइल',
      'prompt_types': 'प्रॉम्प्ट प्रकार',
      'recent_chats': 'अलीकडील चॅट',
      'register': 'नोंदणी करा',
      'roll_back': 'परत जा',
      'settings': 'सेटिंग्ज',
      'sign_in_continue': 'सुरू ठेवण्यासाठी साइन इन करा',
      'sign_up': 'साइन अप',
      'sign_up_to_start': 'सुरुवात करण्यासाठी साइन अप करा',
      'skip': 'वगळा',
      'stop_responding': 'थांबवा',
      'thinking': 'विचार करत आहे...',
      'try_prompt_1': 'व्हायरल ट्विट लिहिण्यासाठी प्रॉम्प्ट तयार करा',
      'try_prompt_2': 'Midjourney इमेज प्रॉम्प्ट तयार करा',
      'try_prompt_3': 'उत्पाद लॉन्चसाठी मार्केटिंग प्रॉम्प्ट तयार करा',
      'try_prompt_4': 'ब्लॉग आउटलाइनसाठी AI प्रॉम्प्ट तयार करा',
      'try_prompts': 'प्रॉम्प्ट वापरून पाहा',
      'type_message': 'संदेश टाइप करा...',
      'welcome_back': 'परत स्वागत आहे',
      'welcome_subtitle': 'तुमचा AI-चालित प्रॉम्प्ट जनरेशन सहाय्यक',
      'welcome_to': 'Vakya Pro मध्ये आपले स्वागत आहे',
      'yes': 'होय',
    },
    'gu': {
      'already_have_account': 'પહેલેથી એકાઉન્ટ છે?',
      'cancel': 'રદ કરો',
      'confirm_logout': 'શું તમે ખરેખર લૉગઆઉટ કરવા માંગો છો?',
      'copied_to_clipboard': 'ક્લિપબોર્ડ પર કૉપિ થયું',
      'create_account': 'એકાઉન્ટ બનાવો',
      'describe_placeholder': 'તમે જે પ્રોમ્પ્ટ બનાવવા માંગો છો તે જણાવો...',
      'describe_prompts_subtitle': 'તમે જે ઇચ્છો છો તે જણાવો અને કોઈ પણ AI ટૂલ માટે ઑપ્ટિમાઇઝ પ્રોમ્પ્ટ મેળવો.',
      'dont_have_account': 'એકાઉન્ટ નથી?',
      'edit': 'સંપાદિત કરો',
      'enter_email': 'ઇમેઇલ દાખલ કરો',
      'coding': 'કોડિંગ',
      'generate_better_prompts': 'વધુ સારા AI પ્રોમ્પ્ટ બનાવો',
      'generate_prompt': 'પ્રોમ્પ્ટ બનાવો',
      'marketing': 'માર્કેટિંગ',
      'get_started': 'શરૂ કરો',
      'language': 'ભાષા',
      'login': 'લૉગિન',
      'logout': 'લૉગઆઉટ',
      'new_chat': 'નવી ચેટ',
      'onboarding_slide1_subtitle': 'કોઈ પણ AI ટૂલ માટે સરળતાથી શક્તિશાળી પ્રોમ્પ્ટ બનાવો',
      'onboarding_slide1_title': 'AI પ્રોમ્પ્ટ જનરેટર',
      'onboarding_slide2_subtitle': 'અમારી માર્ગદર્શિત પ્રક્રિયા સાથે પગલે પગલે સાચો પ્રોમ્પ્ટ બનાવો',
      'onboarding_slide2_title': 'પગલે પગલે માર્ગદર્શન',
      'onboarding_slide3_subtitle': 'હિન્દી, મરાઠી, ગુજરાતી અને વધુ ભારતીય ભાષાઓને સમર્થન કરે છે',
      'onboarding_slide3_title': 'બહુભાષા સમર્થન',
      'or_continue_with': 'અથવા આ સાથે ચાલુ રાખો',
      'password': 'પાસવર્ડ',
      'pre_prompts': 'પૂર્વ-નિર્ધારિત પ્રોમ્પ્ટ',
      'profile': 'પ્રોફાઇલ',
      'prompt_types': 'પ્રોમ્પ્ટ પ્રકારો',
      'recent_chats': 'તાજેતરની ચેટ',
      'register': 'નોંધણી કરો',
      'roll_back': 'પૂર્વવત્ કરો',
      'settings': 'સેટિંગ્સ',
      'sign_in_continue': 'ચાલુ રાખવા માટે સાઇન ઇન કરો',
      'sign_up': 'સાઇન અપ',
      'sign_up_to_start': 'શરૂ કરવા માટે સાઇન અપ કરો',
      'skip': 'છોડો',
      'stop_responding': 'રોકો',
      'thinking': 'વિચારી રહ્યો છું...',
      'try_prompt_1': 'વાઇરલ ટ્વીટ લખવા માટે પ્રોમ્પ્ટ બનાવો',
      'try_prompt_2': 'Midjourney ઇમેજ પ્રોમ્પ્ટ બનાવો',
      'try_prompt_3': 'પ્રોડક્ટ લૉન્ચ માટે માર્કેટિંગ પ્રોમ્પ્ટ બનાવો',
      'try_prompt_4': 'બ્લૉગ આઉટલાઇન માટે AI પ્રોમ્પ્ટ બનાવો',
      'try_prompts': 'પ્રોમ્પ્ટ અજમાવો',
      'type_message': 'સંદેશ ટાઇપ કરો...',
      'welcome_back': 'પાછા આવ્યા, સ્વાગત છે',
      'welcome_subtitle': 'તમારો AI-સંચાલિત પ્રોમ્પ્ટ જનરેશન સહાયક',
      'welcome_to': 'Vakya Pro માં આપનું સ્વાગત છે',
      'yes': 'હા',
    },
    'ta': {
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'cancel': 'ரத்து செய்',
      'confirm_logout': 'நீங்கள் உண்மையிலேயே வெளியேற விரும்புகிறீர்களா?',
      'copied_to_clipboard': 'கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது',
      'create_account': 'கணக்கு உருவாக்கு',
      'describe_placeholder': 'நீங்கள் உருவாக்க விரும்பும் ப்ராம்டை விவரிக்கவும்...',
      'describe_prompts_subtitle': 'நீங்கள் விரும்புவதை விவரியுங்கள், எந்த AI கருவிக்கும் ஒப்டிமைஸ் செய்யப்பட்ட ப்ராம்ட்களைப் பெறுங்கள்.',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'edit': 'திருத்து',
      'enter_email': 'மின்னஞ்சல் உள்ளிடுக',
      'coding': 'கோடிங்',
      'generate_better_prompts': 'சிறந்த AI ப்ராம்ட்களை உருவாக்கு',
      'generate_prompt': 'ப்ராம்ட் உருவாக்கு',
      'marketing': 'மார்க்கெட்டிங்',
      'get_started': 'தொடங்குக',
      'language': 'மொழி',
      'login': 'உள்நுழை',
      'logout': 'வெளியேறு',
      'new_chat': 'புதிய அரட்டை',
      'onboarding_slide1_subtitle': 'எந்த AI கருவிக்கும் சக்திவாய்ந்த ப்ராம்ட்களை எளிதாக உருவாக்குங்கள்',
      'onboarding_slide1_title': 'AI ப்ராம்ட் ஜெனரேட்டர்',
      'onboarding_slide2_subtitle': 'எங்கள் வழிகாட்டும் செயல்முறையுடன் படிப்படியாக சரியான ப்ராம்ட் தயாரிக்கவும்',
      'onboarding_slide2_title': 'படிப்படியான வழிகாட்டுதல்',
      'onboarding_slide3_subtitle': 'இந்தி, மராத்தி, குஜராத்தி மற்றும் பல இந்திய மொழிகளை ஆதரிக்கிறது',
      'onboarding_slide3_title': 'பல மொழி ஆதரவு',
      'or_continue_with': 'அல்லது இதனுடன் தொடரவும்',
      'password': 'கடவுச்சொல்',
      'pre_prompts': 'முன்னமைக்கப்பட்ட ப்ராம்ட்கள்',
      'profile': 'சுயவிவரம்',
      'prompt_types': 'ப்ராம்ட் வகைகள்',
      'recent_chats': 'சமீபத்திய அரட்டைகள்',
      'register': 'பதிவு செய்',
      'roll_back': 'மீட்டமை',
      'settings': 'அமைப்புகள்',
      'sign_in_continue': 'தொடர உள்நுழைக',
      'sign_up': 'பதிவு செய்',
      'sign_up_to_start': 'தொடங்க பதிவு செய்யுங்கள்',
      'skip': 'தவிர்',
      'stop_responding': 'நிறுத்து',
      'thinking': 'யோசிக்கிறேன்...',
      'try_prompt_1': 'வைரல் ட்வீட் எழுதுவதற்கான ப்ராம்ட் உருவாக்கு',
      'try_prompt_2': 'Midjourney படப் ப்ராம்ட் உருவாக்கு',
      'try_prompt_3': 'தயாரிப்பு அறிமுகத்திற்கான மார்க்கெட்டிங் ப்ராம்ட் உருவாக்கு',
      'try_prompt_4': 'வலைப்பதிவு கோட்டிட்டுக்கான AI ப்ராம்ட் உருவாக்கு',
      'try_prompts': 'ப்ராம்ட்களை முயற்சிக்கவும்',
      'type_message': 'செய்தி தட்டச்சு செய்யுங்கள்...',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'welcome_subtitle': 'உங்கள் AI-இயக்கும் ப்ராம்ட் ஜெனரேஷன் உதவியாளர்',
      'welcome_to': 'Vakya Pro-ல் உங்களை வரவேற்கிறோம்',
      'yes': 'ஆம்',
    },
    'te': {
      'already_have_account': 'ఇప్పటికే ఖాతా ఉందా?',
      'cancel': 'రద్దు చేయి',
      'confirm_logout': 'మీరు నిజంగా లాగ్అవుట్ చేయాలనుకుంటున్నారా?',
      'copied_to_clipboard': 'క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది',
      'create_account': 'ఖాతా సృష్టించు',
      'describe_placeholder': 'మీరు సృష్టించాలనుకుంటున్న ప్రాంప్ట్‌ను వివరించండి...',
      'describe_prompts_subtitle': 'మీకు ఏమి కావాలో వివరించండి మరియు ఏ AI సాధనానికైనా ఆప్టిమైజ్ చేసిన ప్రాంప్ట్‌లు పొందండి.',
      'dont_have_account': 'ఖాతా లేదా?',
      'edit': 'సవరించు',
      'enter_email': 'ఇమెయిల్ నమోదు చేయండి',
      'coding': 'కోడింగ్',
      'generate_better_prompts': 'మెరుగైన AI ప్రాంప్ట్‌లు రూపొందించండి',
      'generate_prompt': 'ప్రాంప్ట్ రూపొందించు',
      'marketing': 'మార్కెటింగ్',
      'get_started': 'ప్రారంభించు',
      'language': 'భాష',
      'login': 'లాగిన్',
      'logout': 'లాగ్అవుట్',
      'new_chat': 'కొత్త చాట్',
      'onboarding_slide1_subtitle': 'ఏ AI సాధనానికైనా శక్తివంతమైన ప్రాంప్ట్‌లను సులభంగా రూపొందించండి',
      'onboarding_slide1_title': 'AI ప్రాంప్ట్ జెనరేటర్',
      'onboarding_slide2_subtitle': 'మా మార్గదర్శక ప్రక్రియతో దశల వారీగా సరైన ప్రాంప్ట్ తయారు చేయండి',
      'onboarding_slide2_title': 'దశల వారీ మార్గదర్శనం',
      'onboarding_slide3_subtitle': 'హిందీ, మరాఠీ, గుజరాతీ మరియు మరిన్ని భారతీయ భాషలకు మద్దతు ఇస్తుంది',
      'onboarding_slide3_title': 'బహుభాషా మద్దతు',
      'or_continue_with': 'లేదా దీనితో కొనసాగించండి',
      'password': 'పాస్‌వర్డ్',
      'pre_prompts': 'ముందే నిర్ణయించిన ప్రాంప్ట్‌లు',
      'profile': 'ప్రొఫైల్',
      'prompt_types': 'ప్రాంప్ట్ రకాలు',
      'recent_chats': 'ఇటీవలి చాట్‌లు',
      'register': 'నమోదు చేసుకో',
      'roll_back': 'వెనక్కు తీసుకో',
      'settings': 'సెట్టింగులు',
      'sign_in_continue': 'కొనసాగించడానికి సైన్ ఇన్ చేయండి',
      'sign_up': 'సైన్ అప్',
      'sign_up_to_start': 'ప్రారంభించడానికి సైన్ అప్ చేయండి',
      'skip': 'దాటవేయి',
      'stop_responding': 'ఆపు',
      'thinking': 'ఆలోచిస్తున్నాను...',
      'try_prompt_1': 'వైరల్ ట్వీట్‌లు రాయడానికి ప్రాంప్ట్ తయారు చేయండి',
      'try_prompt_2': 'Midjourney చిత్రం ప్రాంప్ట్ రూపొందించండి',
      'try_prompt_3': 'ఉత్పత్తి లాంచ్ కోసం మార్కెటింగ్ ప్రాంప్ట్ తయారు చేయండి',
      'try_prompt_4': 'బ్లాగ్ అవుట్‌లైన్ కోసం AI ప్రాంప్ట్ రూపొందించండి',
      'try_prompts': 'ప్రాంప్ట్‌లు ప్రయత్నించండి',
      'type_message': 'సందేశం టైప్ చేయండి...',
      'welcome_back': 'తిరిగి స్వాగతం',
      'welcome_subtitle': 'మీ AI-ఆధారిత ప్రాంప్ట్ జెనరేషన్ సహాయకుడు',
      'welcome_to': 'Vakya Pro కి స్వాగతం',
      'yes': 'అవును',
    },
    'bn': {
      'already_have_account': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
      'cancel': 'বাতিল করুন',
      'confirm_logout': 'আপনি কি সত্যিই লগআউট করতে চান?',
      'copied_to_clipboard': 'ক্লিপবোর্ডে কপি করা হয়েছে',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'describe_placeholder': 'আপনি যে প্রম্পট তৈরি করতে চান তা বর্ণনা করুন...',
      'describe_prompts_subtitle': 'আপনি যা চান তা বর্ণনা করুন এবং যেকোনো AI টুলের জন্য অপ্টিমাইজড প্রম্পট পান।',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'edit': 'সম্পাদনা করুন',
      'enter_email': 'ইমেইল লিখুন',
      'coding': 'কোডিং',
      'generate_better_prompts': 'উন্নত AI প্রম্পট তৈরি করুন',
      'generate_prompt': 'প্রম্পট তৈরি করুন',
      'marketing': 'মার্কেটিং',
      'get_started': 'শুরু করুন',
      'language': 'ভাষা',
      'login': 'লগইন',
      'logout': 'লগআউট',
      'new_chat': 'নতুন চ্যাট',
      'onboarding_slide1_subtitle': 'যেকোনো AI টুলের জন্য সহজেই শক্তিশালী প্রম্পট তৈরি করুন',
      'onboarding_slide1_title': 'AI প্রম্পট জেনারেটর',
      'onboarding_slide2_subtitle': 'আমাদের গাইডেড প্রক্রিয়ায় ধাপে ধাপে সঠিক প্রম্পট তৈরি করুন',
      'onboarding_slide2_title': 'ধাপে ধাপে গাইডেন্স',
      'onboarding_slide3_subtitle': 'হিন্দি, মারাঠি, গুজরাটি এবং আরও ভারতীয় ভাষা সমর্থন করে',
      'onboarding_slide3_title': 'বহুভাষা সমর্থন',
      'or_continue_with': 'অথবা এর সাথে চালিয়ে যান',
      'password': 'পাসওয়ার্ড',
      'pre_prompts': 'পূর্বনির্ধারিত প্রম্পট',
      'profile': 'প্রোফাইল',
      'prompt_types': 'প্রম্পট ধরন',
      'recent_chats': 'সাম্প্রতিক চ্যাট',
      'register': 'নিবন্ধন করুন',
      'roll_back': 'ফিরিয়ে নিন',
      'settings': 'সেটিংস',
      'sign_in_continue': 'চালিয়ে যেতে সাইন ইন করুন',
      'sign_up': 'সাইন আপ',
      'sign_up_to_start': 'শুরু করতে সাইন আপ করুন',
      'skip': 'এড়িয়ে যান',
      'stop_responding': 'থামুন',
      'thinking': 'ভাবছি...',
      'try_prompt_1': 'ভাইরাল টুইট লেখার জন্য প্রম্পট তৈরি করুন',
      'try_prompt_2': 'Midjourney ছবির প্রম্পট তৈরি করুন',
      'try_prompt_3': 'পণ্য লঞ্চের জন্য মার্কেটিং প্রম্পট তৈরি করুন',
      'try_prompt_4': 'ব্লগ আউটলাইনের জন্য AI প্রম্পট তৈরি করুন',
      'try_prompts': 'প্রম্পট চেষ্টা করুন',
      'type_message': 'একটি বার্তা টাইপ করুন...',
      'welcome_back': 'আবার স্বাগতম',
      'welcome_subtitle': 'আপনার AI-চালিত প্রম্পট জেনারেশন সহকারী',
      'welcome_to': 'Vakya Pro তে স্বাগতম',
      'yes': 'হ্যাঁ',
    },
    'kn': {
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
      'cancel': 'ರದ್ದು ಮಾಡಿ',
      'confirm_logout': 'ನೀವು ನಿಜವಾಗಿಯೂ ಲಾಗ್ಔಟ್ ಮಾಡಲು ಬಯಸುತ್ತೀರಾ?',
      'copied_to_clipboard': 'ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಲಾಗಿದೆ',
      'create_account': 'ಖಾತೆ ರಚಿಸಿ',
      'describe_placeholder': 'ನೀವು ರಚಿಸಲು ಬಯಸುವ ಪ್ರಾಂಪ್ಟ್ ವಿವರಿಸಿ...',
      'describe_prompts_subtitle': 'ನೀವು ಏನು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ವಿವರಿಸಿ ಮತ್ತು ಯಾವುದೇ AI ಉಪಕರಣಕ್ಕೆ ಆಪ್ಟಿಮೈಸ್ ಪ್ರಾಂಪ್ಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'dont_have_account': 'ಖಾತೆ ಇಲ್ಲವೇ?',
      'edit': 'ಸಂಪಾದಿಸಿ',
      'enter_email': 'ಇಮೇಲ್ ನಮೂದಿಸಿ',
      'coding': 'ಕೋಡಿಂಗ್',
      'generate_better_prompts': 'ಉತ್ತಮ AI ಪ್ರಾಂಪ್ಟ್‌ಗಳನ್ನು ರಚಿಸಿ',
      'generate_prompt': 'ಪ್ರಾಂಪ್ಟ್ ರಚಿಸಿ',
      'marketing': 'ಮಾರ್ಕೆಟಿಂಗ್',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'language': 'ಭಾಷೆ',
      'login': 'ಲಾಗಿನ್',
      'logout': 'ಲಾಗ್ಔಟ್',
      'new_chat': 'ಹೊಸ ಚಾಟ್',
      'onboarding_slide1_subtitle': 'ಯಾವುದೇ AI ಉಪಕರಣಕ್ಕೆ ಸುಲಭವಾಗಿ ಶಕ್ತಿಶಾಲಿ ಪ್ರಾಂಪ್ಟ್‌ಗಳನ್ನು ರಚಿಸಿ',
      'onboarding_slide1_title': 'AI ಪ್ರಾಂಪ್ಟ್ ಜನರೇಟರ್',
      'onboarding_slide2_subtitle': 'ನಮ್ಮ ಮಾರ್ಗದರ್ಶಿ ಪ್ರಕ್ರಿಯೆಯೊಂದಿಗೆ ಹಂತ ಹಂತವಾಗಿ ಸರಿಯಾದ ಪ್ರಾಂಪ್ಟ್ ತಯಾರಿಸಿ',
      'onboarding_slide2_title': 'ಹಂತ ಹಂತದ ಮಾರ್ಗದರ್ಶನ',
      'onboarding_slide3_subtitle': 'ಹಿಂದಿ, ಮರಾಠಿ, ಗುಜರಾತಿ ಮತ್ತು ಹೆಚ್ಚಿನ ಭಾರತೀಯ ಭಾಷೆಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ',
      'onboarding_slide3_title': 'ಬಹುಭಾಷಾ ಬೆಂಬಲ',
      'or_continue_with': 'ಅಥವಾ ಇದರೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'pre_prompts': 'ಪೂರ್ವ-ನಿರ್ಧಾರಿತ ಪ್ರಾಂಪ್ಟ್‌ಗಳು',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'prompt_types': 'ಪ್ರಾಂಪ್ಟ್ ವಿಧಗಳು',
      'recent_chats': 'ಇತ್ತೀಚಿನ ಚಾಟ್‌ಗಳು',
      'register': 'ನೋಂದಾಯಿಸಿ',
      'roll_back': 'ಹಿಂದಕ್ಕೆ ತೆಗೆದುಕೊಳ್ಳಿ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'sign_in_continue': 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'sign_up': 'ಸೈನ್ ಅಪ್',
      'sign_up_to_start': 'ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'skip': 'ಬಿಟ್ಟುಬಿಡಿ',
      'stop_responding': 'ನಿಲ್ಲಿಸಿ',
      'thinking': 'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...',
      'try_prompt_1': 'ವೈರಲ್ ಟ್ವೀಟ್‌ಗಳನ್ನು ಬರೆಯಲು ಪ್ರಾಂಪ್ಟ್ ರಚಿಸಿ',
      'try_prompt_2': 'Midjourney ಚಿತ್ರ ಪ್ರಾಂಪ್ಟ್ ರಚಿಸಿ',
      'try_prompt_3': 'ಉತ್ಪನ್ನ ಲಾಂಚ್‌ಗಾಗಿ ಮಾರ್ಕೆಟಿಂಗ್ ಪ್ರಾಂಪ್ಟ್ ರಚಿಸಿ',
      'try_prompt_4': 'ಬ್ಲಾಗ್ ಔಟ್‌ಲೈನ್‌ಗಾಗಿ AI ಪ್ರಾಂಪ್ಟ್ ರಚಿಸಿ',
      'try_prompts': 'ಪ್ರಾಂಪ್ಟ್‌ಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ',
      'type_message': 'ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...',
      'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
      'welcome_subtitle': 'ನಿಮ್ಮ AI-ಚಾಲಿತ ಪ್ರಾಂಪ್ಟ್ ಜನರೇಷನ್ ಸಹಾಯಕ',
      'welcome_to': 'Vakya Pro ಗೆ ಸ್ವಾಗತ',
      'yes': 'ಹೌದು',
    },
    'ml': {
      'already_have_account': 'ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?',
      'cancel': 'റദ്ദാക്കുക',
      'confirm_logout': 'നിങ്ങൾ ശരിക്കും ലോഗൗട്ട് ചെയ്യാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
      'copied_to_clipboard': 'ക്ലിപ്പ്‌ബോർഡിലേക്ക് പകർത്തി',
      'create_account': 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
      'describe_placeholder': 'നിങ്ങൾ ഉണ്ടാക്കാൻ ആഗ്രഹിക്കുന്ന പ്രോംപ്റ്റ് വിവരിക്കുക...',
      'describe_prompts_subtitle': 'നിങ്ങൾക്ക് ആവശ്യമുള്ളത് വിവരിക്കൂ, ഏത് AI ടൂളിനും ഒപ്റ്റിമൈസ് ചെയ്ത പ്രോംപ്റ്റുകൾ നേടൂ.',
      'dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ?',
      'edit': 'തിരുത്തുക',
      'enter_email': 'ഇമെയിൽ നൽകുക',
      'coding': 'കോഡിംഗ്',
      'generate_better_prompts': 'മികച്ച AI പ്രോംപ്റ്റുകൾ സൃഷ്ടിക്കുക',
      'generate_prompt': 'പ്രോംപ്റ്റ് സൃഷ്ടിക്കുക',
      'marketing': 'മാർക്കറ്റിംഗ്',
      'get_started': 'ആരംഭിക്കുക',
      'language': 'ഭാഷ',
      'login': 'ലോഗിൻ',
      'logout': 'ലോഗൗട്ട്',
      'new_chat': 'പുതിയ ചാറ്റ്',
      'onboarding_slide1_subtitle': 'ഏത് AI ടൂളിനും ശക്തമായ പ്രോംപ്റ്റുകൾ എളുപ്പത്തിൽ സൃഷ്ടിക്കുക',
      'onboarding_slide1_title': 'AI പ്രോംപ്റ്റ് ജനറേറ്റർ',
      'onboarding_slide2_subtitle': 'ഞങ്ങളുടെ ഗൈഡഡ് പ്രക്രിയ ഉപയോഗിച്ച് ഘട്ടം ഘട്ടമായി ശരിയായ പ്രോംപ്റ്റ് ഉണ്ടാക്കുക',
      'onboarding_slide2_title': 'ഘട്ടം ഘട്ടമായ മാർഗ്ഗനിർദ്ദേശം',
      'onboarding_slide3_subtitle': 'ഹിന്ദി, മറാഠി, ഗുജറാത്തി തുടങ്ങിയ ഇന്ത്യൻ ഭാഷകൾ പിന്തുണയ്ക്കുന്നു',
      'onboarding_slide3_title': 'ബഹുഭാഷ പിന്തുണ',
      'or_continue_with': 'അല്ലെങ്കിൽ ഇതോടൊപ്പം തുടരുക',
      'password': 'പാസ്‌വേഡ്',
      'pre_prompts': 'മുൻകൂട്ടി നിശ്ചയിച്ച പ്രോംപ്റ്റുകൾ',
      'profile': 'പ്രൊഫൈൽ',
      'prompt_types': 'പ്രോംപ്റ്റ് തരങ്ങൾ',
      'recent_chats': 'സമീപകാല ചാറ്റുകൾ',
      'register': 'രജിസ്റ്റർ ചെയ്യുക',
      'roll_back': 'പഴയപടിയാക്കുക',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'sign_in_continue': 'തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
      'sign_up': 'സൈൻ അപ്പ്',
      'sign_up_to_start': 'ആരംഭിക്കാൻ സൈൻ അപ്പ് ചെയ്യുക',
      'skip': 'ഒഴിവാക്കുക',
      'stop_responding': 'നിർത്തുക',
      'thinking': 'ചിന്തിക്കുന്നു...',
      'try_prompt_1': 'വൈറൽ ട്വീറ്റുകൾ എഴുതാൻ ഒരു പ്രോംപ്റ്റ് ഉണ്ടാക്കുക',
      'try_prompt_2': 'Midjourney ചിത്ര പ്രോംപ്റ്റ് സൃഷ്ടിക്കുക',
      'try_prompt_3': 'ഉൽപ്പന്ന ലോഞ്ചിനായി മാർക്കറ്റിംഗ് പ്രോംപ്റ്റ് ഉണ്ടാക്കുക',
      'try_prompt_4': 'ബ്ലോഗ് ഔട്ട്‌ലൈനിനായി AI പ്രോംപ്റ്റ് സൃഷ്ടിക്കുക',
      'try_prompts': 'പ്രോംപ്റ്റുകൾ പരീക്ഷിക്കുക',
      'type_message': 'ഒരു സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'welcome_back': 'തിരികെ സ്വാഗതം',
      'welcome_subtitle': 'നിങ്ങളുടെ AI-ഊർജ്ജിത പ്രോംപ്റ്റ് ജനറേഷൻ അസിസ്റ്റന്റ്',
      'welcome_to': 'Vakya Pro-ലേക്ക് സ്വാഗതം',
      'yes': 'അതെ',
    },
    'pa': {
      'already_have_account': 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'confirm_logout': 'ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ ਲੌਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'copied_to_clipboard': 'ਕਲਿੱਪਬੋਰਡ ਤੇ ਕਾਪੀ ਕੀਤਾ',
      'create_account': 'ਖਾਤਾ ਬਣਾਓ',
      'describe_placeholder': 'ਤੁਸੀਂ ਜੋ ਪ੍ਰੋਂਪਟ ਬਣਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ ਉਹ ਦੱਸੋ...',
      'describe_prompts_subtitle': 'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕੀ ਚਾਹੁੰਦੇ ਹੋ ਅਤੇ ਕਿਸੇ ਵੀ AI ਟੂਲ ਲਈ ਅਨੁਕੂਲ ਪ੍ਰੋਂਪਟ ਪ੍ਰਾਪਤ ਕਰੋ।',
      'dont_have_account': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
      'edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
      'enter_email': 'ਈਮੇਲ ਦਾਖਲ ਕਰੋ',
      'coding': 'ਕੋਡਿੰਗ',
      'generate_better_prompts': 'ਬਿਹਤਰ AI ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'generate_prompt': 'ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'marketing': 'ਮਾਰਕੀਟਿੰਗ',
      'get_started': 'ਸ਼ੁਰੂ ਕਰੋ',
      'language': 'ਭਾਸ਼ਾ',
      'login': 'ਲੌਗਿਨ',
      'logout': 'ਲੌਗਆਉਟ',
      'new_chat': 'ਨਵੀਂ ਗੱਲਬਾਤ',
      'onboarding_slide1_subtitle': 'ਕਿਸੇ ਵੀ AI ਟੂਲ ਲਈ ਆਸਾਨੀ ਨਾਲ ਸ਼ਕਤੀਸ਼ਾਲੀ ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'onboarding_slide1_title': 'AI ਪ੍ਰੋਂਪਟ ਜਨਰੇਟਰ',
      'onboarding_slide2_subtitle': 'ਸਾਡੀ ਮਾਰਗਦਰਸ਼ਕ ਪ੍ਰਕਿਰਿਆ ਨਾਲ ਕਦਮ-ਦਰ-ਕਦਮ ਸਹੀ ਪ੍ਰੋਂਪਟ ਤਿਆਰ ਕਰੋ',
      'onboarding_slide2_title': 'ਕਦਮ-ਦਰ-ਕਦਮ ਮਾਰਗਦਰਸ਼ਨ',
      'onboarding_slide3_subtitle': 'ਹਿੰਦੀ, ਮਰਾਠੀ, ਗੁਜਰਾਤੀ ਅਤੇ ਹੋਰ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਦਾ ਸਮਰਥਨ ਕਰਦਾ ਹੈ',
      'onboarding_slide3_title': 'ਬਹੁਭਾਸ਼ਾ ਸਮਰਥਨ',
      'or_continue_with': 'ਜਾਂ ਇਸ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      'password': 'ਪਾਸਵਰਡ',
      'pre_prompts': 'ਪਹਿਲਾਂ ਤੋਂ ਤੈਅ ਪ੍ਰੋਂਪਟ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'prompt_types': 'ਪ੍ਰੋਂਪਟ ਕਿਸਮਾਂ',
      'recent_chats': 'ਹਾਲੀਆ ਗੱਲਬਾਤਾਂ',
      'register': 'ਰਜਿਸਟਰ ਕਰੋ',
      'roll_back': 'ਵਾਪਸ ਕਰੋ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'sign_in_continue': 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
      'sign_up': 'ਸਾਈਨ ਅੱਪ',
      'sign_up_to_start': 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਸਾਈਨ ਅੱਪ ਕਰੋ',
      'skip': 'ਛੱਡੋ',
      'stop_responding': 'ਰੋਕੋ',
      'thinking': 'ਸੋਚ ਰਿਹਾ ਹਾਂ...',
      'try_prompt_1': 'ਵਾਇਰਲ ਟਵੀਟ ਲਿਖਣ ਲਈ ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'try_prompt_2': 'Midjourney ਤਸਵੀਰ ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'try_prompt_3': 'ਉਤਪਾਦ ਲਾਂਚ ਲਈ ਮਾਰਕੀਟਿੰਗ ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'try_prompt_4': 'ਬਲੌਗ ਆਉਟਲਾਈਨ ਲਈ AI ਪ੍ਰੋਂਪਟ ਬਣਾਓ',
      'try_prompts': 'ਪ੍ਰੋਂਪਟ ਅਜ਼ਮਾਓ',
      'type_message': 'ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      'welcome_back': 'ਵਾਪਸ ਸੁਆਗਤ ਹੈ',
      'welcome_subtitle': 'ਤੁਹਾਡਾ AI-ਸੰਚਾਲਿਤ ਪ੍ਰੋਂਪਟ ਜਨਰੇਸ਼ਨ ਸਹਾਇਕ',
      'welcome_to': 'Vakya Pro ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
      'yes': 'ਹਾਂ',
    },
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
