class AppLocalization {
  final String language;

  AppLocalization(this.language);

  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'settings': 'Settings',
      'language': 'Language',
      'profile': 'Profile',
      'logout': 'Log Out',
      'new_chat': 'New Chat',
      'recent_chats': 'Recent Chats',
      'pre_prompts': 'Pre Prompts',
      'type_message': 'Type a message...',
      'welcome': 'Welcome!',
      'confirm_logout': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'thinking': 'Thinking...',
    },
    'Hindi': {
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'profile': 'प्रोफ़ाइल',
      'logout': 'लॉग आउट',
      'new_chat': 'नया चैट',
      'recent_chats': 'हाल के चैट',
      'pre_prompts': 'प्री प्रॉम्प्ट्स',
      'type_message': 'संदेश लिखें...',
      'welcome': 'स्वागत है!',
      'confirm_logout': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'yes': 'हाँ',
      'thinking': 'सोच रहा हूँ...',
    },
    'Marathi': {
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'profile': 'प्रोफाइल',
      'logout': 'लॉग आउट',
      'new_chat': 'नवीन चॅट',
      'recent_chats': 'अलीकडील चॅट्स',
      'pre_prompts': 'प्री प्रॉम्प्ट्स',
      'type_message': 'संदेश टाइप करा...',
      'welcome': 'स्वागत आहे!',
      'confirm_logout': 'आपण नक्की लॉग आउट करू इच्छिता?',
      'cancel': 'रद्द करा',
      'yes': 'हो',
      'thinking': 'विचार करत आहे...',
    },
    'Gujarati': {
      'settings': 'સેટિંગ્સ',
      'language': 'ભાષા',
      'profile': 'પ્રોફાઇલ',
      'logout': 'લોગ આઉટ',
      'new_chat': 'નવી ચેટ',
      'recent_chats': 'તાજેતરની ચેટ્સ',
      'pre_prompts': 'પ્રી પ્રોમ્પ્ટ્સ',
      'type_message': 'સંદેશ લખો...',
      'welcome': 'સ્વાગત છે!',
      'confirm_logout': 'શું તમે ખરેખર લોગ આઉટ કરવા માંગો છો?',
      'cancel': 'રદ કરો',
      'yes': 'હા',
      'thinking': 'વિચારી રહ્યો છું...',
    },
    'Tamil': {
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'new_chat': 'புதிய அரட்டை',
      'recent_chats': 'சமீபத்திய அரட்டைகள்',
      'pre_prompts': 'முன் தூண்டுதல்கள்',
      'type_message': 'செய்தியைத் தட்டச்சு செய்க...',
      'welcome': 'வரவேற்கிறோம்!',
      'confirm_logout': 'நிச்சயமாக வெளியேற வேண்டுமா?',
      'cancel': 'ரத்து செய்',
      'yes': 'ஆம்',
      'thinking': 'யோசிக்கிறேன்...',
    },
    'Telugu': {
      'settings': 'సెట్టింగులు',
      'language': 'భాష',
      'profile': 'ప్రొఫైల్',
      'logout': 'లాగ్ అవుట్',
      'new_chat': 'కొత్త చాట్',
      'recent_chats': 'ఇటీవలి చాట్లు',
      'pre_prompts': 'ముందస్తు ప్రాంప్ట్‌లు',
      'type_message': 'సందేశాన్ని టైప్ చేయండి...',
      'welcome': 'స్వాగతం!',
      'confirm_logout': 'మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
      'cancel': 'రద్దు చేయి',
      'yes': 'అవును',
      'thinking': 'ఆలోచిస్తున్నాను...',
    },
    'Bengali': {
      'settings': 'সেটিংস',
      'language': 'ভাষা',
      'profile': 'প্রোফাইল',
      'logout': 'লগ আউট',
      'new_chat': 'নতুন চ্যাট',
      'recent_chats': 'সাম্প্রতিক চ্যাট',
      'pre_prompts': 'প্রাক নির্দেশাবলী',
      'type_message': 'একটি বার্তা লিখুন...',
      'welcome': 'স্বাগতম!',
      'confirm_logout': 'আপনি কি নিশ্চিত যে আপনি লগ আউট করতে চান?',
      'cancel': 'বাতিল করুন',
      'yes': 'হ্যাঁ',
      'thinking': 'ভাবছি...',
    },
    'Kannada': {
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'new_chat': 'ಹೊಸ ಚಾಟ್',
      'recent_chats': 'ಇತ್ತೀಚಿನ ಚಾಟ್‌ಗಳು',
      'pre_prompts': 'ಪೂರ್ವ ಪ್ರಾಂಪ್ಟ್‌ಗಳು',
      'type_message': 'ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
      'welcome': 'ಸ್ವಾಗತ!',
      'confirm_logout': 'ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
      'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
      'yes': 'ಹೌದು',
      'thinking': 'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...',
    },
    'Malayalam': {
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'profile': 'പ്രൊഫൈൽ',
      'logout': 'ലോഗ് ഔട്ട്',
      'new_chat': 'புതിയ ചാറ്റ്',
      'recent_chats': 'സമീപകാല ചാറ്റുകൾ',
      'pre_prompts': 'പ്രീ പ്രോംപ്റ്റുകൾ',
      'type_message': 'സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'welcome': 'സ്വാഗതം!',
      'confirm_logout': 'നിങ്ങൾ ലോഗ് ഔട്ട് ചെയ്യാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
      'cancel': 'റദ്ദാക്കുക',
      'yes': 'അതെ',
      'thinking': 'ചിന്തിക്കുന്നു...',
    },
    'Punjabi': {
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'language': 'ਭਾਸ਼ਾ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'logout': 'ਲੌਗ ਆਉਟ',
      'new_chat': 'ਨਵਾਂ ਚੈਟ',
      'recent_chats': 'ਹਾਲੀਆ ਚੈਟਾਂ',
      'pre_prompts': 'ਪ੍ਰੀ ਪ੍ਰੋਂਪਟ',
      'type_message': 'ਸੁਨੇਹਾ ਲਿਖੋ...',
      'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ!',
      'confirm_logout': 'ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਲੌਗ ਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'yes': 'ਹਾਂ',
      'thinking': 'ਸੋਚ ਰਿਹਾ ਹਾਂ...',
    },
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ?? _localizedValues['English']![key]!;
  }
}
